antsApplyTransforms -d 3 -e 0 -i /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_MTRmap.nii.gz -r /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/sub-invivo/ses-vendorSKYtest/anat/sub-invivo_ses-vendorSKYtest_flip-02_mt-off_MTS.nii -o /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_space-test_MTRmap.nii.gz -t /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/ANTs/sub-invivo/ses-vendorSKY/ses-vendorSKY_retest_to_test_displacement.mat0GenericAffine.mat
antsApplyTransforms -d 3 -e 0 -i /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_T1map.nii.gz -r /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/sub-invivo/ses-vendorSKYtest/anat/sub-invivo_ses-vendorSKYtest_flip-02_mt-off_MTS.nii -o /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_space-test_T1map.nii.gz -t /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/ANTs/sub-invivo/ses-vendorSKY/ses-vendorSKY_retest_to_test_displacement.mat0GenericAffine.mat
antsApplyTransforms -d 3 -e 0 -i /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_MTsat.nii.gz -r /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/sub-invivo/ses-vendorSKYtest/anat/sub-invivo_ses-vendorSKYtest_flip-02_mt-off_MTS.nii -o /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_space-test_MTsat.nii.gz -t /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/ANTs/sub-invivo/ses-vendorSKY/ses-vendorSKY_retest_to_test_displacement.mat0GenericAffine.mat
antsApplyTransforms -d 3 -e 0 -i /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_desc-b1corrected_T1map.nii.gz -r /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/sub-invivo/ses-vendorSKYtest/anat/sub-invivo_ses-vendorSKYtest_flip-02_mt-off_MTS.nii -o /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_desc-b1corrected_space-test_T1map.nii.gz -t /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/ANTs/sub-invivo/ses-vendorSKY/ses-vendorSKY_retest_to_test_displacement.mat0GenericAffine.mat
antsApplyTransforms -d 3 -e 0 -i /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_desc-b1corrected_MTsat.nii.gz -r /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/sub-invivo/ses-vendorSKYtest/anat/sub-invivo_ses-vendorSKYtest_flip-02_mt-off_MTS.nii -o /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_desc-b1corrected_space-test_MTsat.nii.gz -t /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/ANTs/sub-invivo/ses-vendorSKY/ses-vendorSKY_retest_to_test_displacement.mat0GenericAffine.mat
antsApplyTransforms -d 3 -e 0 -i /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-rthSKYretest/fmap/sub-invivo_ses-rthSKYretest_desc-resampledfiltered_TB1map.nii.gz -r /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/sub-invivo/ses-rthSKYtest/anat/sub-invivo_ses-rthSKYtest_flip-02_mt-off_MTS.nii.gz -o /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-rthSKYretest/fmap/sub-invivo_ses-rthSKYretest_desc-resampledfiltered_space-test_TB1map.nii.gz -t /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/ANTs/sub-invivo/ses-rthSKY/ses-rthSKY_retest_to_test_displacement.mat0GenericAffine.mat


antsApplyTransforms -d 3 -e 0 -i /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_desc-cfb1corrected_MTsat.nii.gz -r /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/sub-invivo/ses-vendorSKYtest/anat/sub-invivo_ses-vendorSKYtest_flip-02_mt-off_MTS.nii -o /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/qMRLab/sub-invivo/ses-vendorSKYretest/anat/sub-invivo_ses-vendorSKYretest_desc-cfb1corrected_space-test_MTsat.nii.gz -t /Users/agah/Desktop/KuzuData/PHD_DATA/ds-venus/derivatives/ANTs/sub-invivo/ses-vendorSKY/ses-vendorSKY_retest_to_test_displacement.mat0GenericAffine.mat
