channels:
  - conda-forge
  - default
dependencies:
  - r-base=4.0
  - r-tidyverse=1.3.1
  - r-dplyr=1.0.7
  - r-PairedData=1.1.1
  - r-irkernel=1.2.0
  - r-tibble=3.1.4
  - r-plotly=4.10.0
  - r-ggplot2=3.3.5
  - r-cowplot=1.1.1
  - r-R.matlab=3.6.2
  - r-htmlwidgets=1.5.4
  - python=3.6
  - pip
  - pip:
    - matplotlib==3.1.1
    - pandas==0.25.3
    - numpy==1.16.5
    - plotly==4.1.0
    - scipy==1.3.1
    - tables==3.5.2
    - urllib3==1.24.2
