channels:
  - conda-forge
  - default
dependencies:
  - python=3.6
  - jupyter_client=7.1.0
  - jupyter_server=1.13.1
  - pip
  - pip:
    - matplotlib==3.1.1
    - pandas==0.25.3
    - numpy==1.16.5
    - plotly==4.14.0
    - scipy==1.3.1
    - tables==3.5.2
    - urllib3==1.24.2
    - repo2data
    - jupyter-book==0.12.1
