install.packages("plyr")
install.packages("gridExtra")
install.packages("repr")
install.packages("png")
install.packages("dplyr")
install.packages("pairedData")
install.packages("R.matlab")
install.packages("irkernel")
install.packages("tibble")
install.packages("plotly")
install.packages("ggplot2")
install.packages("cowplot")
install.packages("htmlwidgets")

install.packages("devtools")
devtools::install_github("GRousselet/rogme")